apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: 059325865468.dkr.ecr.ap-south-1.amazonaws.com/spring-petclinic:43
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

